package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Promote_Snapshot'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Promote_Snapshot")) {
    requirements {
        add {
            matches("teamcity.agent.name", "dev3-agent1", "TEMPLATE_RQ_2")
        }
    }
}
