package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GitHubVcsRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GitHubVcsRoot")) {
    val expected = GitVcsRoot({
        id("GitHubVcsRoot")
        name = "Buildship"
        url = "https://gradlewaregitbot@github.com/eclipse/buildship.git"
        branchSpec = "+:refs/heads/*"
        userForTags = "Gradleware GitHubVcsRoot Bot <gradlewaregitbot@gradleware.com>"
        agentGitPath = "%env.TEAMCITY_GIT_PATH%"
        agentCleanFilesPolicy = GitVcsRoot.AgentCleanFilesPolicy.NON_IGNORED_ONLY
        useMirrors = false
        authMethod = password {
            userName = "gradlewaregitbot"
            password = "credentialsJSON:4da2f871-8c1f-40d7-a147-860ebfae275e"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = anonymous()
        param("secure:password", "")
        param("username", "")
    }

}
